services:
  mysql:
    image: mysql:8.0
    container_name: fintrack-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: fintrack_identity
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-p123456"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: fintrack-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fintrack-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD","rabbitmq-diagnostics","ping"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  # ========================
  # Backend services
  # ========================

  identity-service:
    image: ghcr.io/liananddandan/identity-service:${IDENTITY_SERVICE_VERSION}
    container_name: fintrack-identity
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      Frontend__PortalBaseUrl: ${ACCOUNT_FRONTEND_BASE_URL}
      ConnectionStrings__DefaultConnection: server=mysql;port=3306;database=fintrack_identity;user=root;password=${MYSQL_ROOT_PASSWORD}
      ConnectionStrings__Redis: redis:6379
      CAP__RabbitMQ__HostName: rabbitmq
      CAP__RabbitMQ__UserName: ${RABBITMQ_USERNAME}
      CAP__RabbitMQ__Password: ${RABBITMQ_PASSWORD}
      CAP__DefaultGroup: identity.service
      Turnstile__SecretKey: ${TURNSTILE_SECRET_KEY}
      InternalApi__ApiKey: ${IDENTITY_INTERNAL_API_KEY}
    ports:
      - "5100:8080"

  transaction-service:
    image: ghcr.io/liananddandan/transaction-service:${TRANSACTION_SERVICE_VERSION}
    container_name: fintrack-transaction
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: server=mysql;port=3306;database=fintrack_transaction;user=root;password=${MYSQL_ROOT_PASSWORD}
      CAP__RabbitMQ__HostName: rabbitmq
      CAP__RabbitMQ__UserName: ${RABBITMQ_USERNAME}
      CAP__RabbitMQ__Password: ${RABBITMQ_PASSWORD}
      CAP__DefaultGroup: transaction.service
    ports:
      - "5101:8080"

  auditlog-service:
    image: ghcr.io/liananddandan/auditlog-service:${AUDITLOG_SERVICE_VERSION}
    container_name: fintrack-auditlog
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: server=mysql;port=3306;database=fintrack_audit;user=root;password=${MYSQL_ROOT_PASSWORD}
      CAP__RabbitMQ__HostName: rabbitmq
      CAP__RabbitMQ__UserName: ${RABBITMQ_USERNAME}
      CAP__RabbitMQ__Password: ${RABBITMQ_PASSWORD}
      CAP__DefaultGroup: audit-log.service
    ports:
      - "5102:8080"

  notification-service:
    image: ghcr.io/liananddandan/notification-service:${NOTIFICATION_SERVICE_VERSION}
    container_name: fintrack-notification
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      CAP__RabbitMQ__HostName: rabbitmq
      CAP__RabbitMQ__UserName: ${RABBITMQ_USERNAME}
      CAP__RabbitMQ__Password: ${RABBITMQ_PASSWORD}
      CAP__DefaultGroup: notification.service
      Resend__ApiKey: ${RESEND_API_KEY}
      Email__Provider: Resend
      Email__FromEmail: ${EMAIL_FROM_ADDRESS}
      Email__FromName: ${EMAIL_FROM_NAME}
      ConnectionStrings__DefaultConnection: server=mysql;port=3306;database=fintrack_notification;user=root;password=${MYSQL_ROOT_PASSWORD}
    ports:
      - "5103:8080"
      
  platform-service:
    image: ghcr.io/liananddandan/platform-service:${PLATFORM_SERVICE_VERSION}
    container_name: fintrack-platform
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: server=mysql;port=3306;database=fintrack_platform;user=root;password=${MYSQL_ROOT_PASSWORD}
      CAP__RabbitMQ__HostName: rabbitmq
      CAP__RabbitMQ__UserName: ${RABBITMQ_USERNAME}
      CAP__RabbitMQ__Password: ${RABBITMQ_PASSWORD}
      CAP__RabbitMQ__VirtualHost: /
      CAP__DefaultGroup: platform.service
      IdentityService__BaseUrl: http://identity-service:8080
      IdentityService__InternalApiKey: ${IDENTITY_INTERNAL_API_KEY}
    ports:
      - "5104:8080"    
    
  
  # ========================
  # API Gateway
  # ========================

  gateway:
    image: ghcr.io/liananddandan/gateway:${GATEWAY_VERSION}
    container_name: fintrack-gateway
    depends_on:
      identity-service:
        condition: service_started
      transaction-service:
        condition: service_started
      auditlog-service:
        condition: service_started
      notification-service:
        condition: service_started
      redis:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Redis: redis:6379
      ReverseProxy__Clusters__identityCluster__Destinations__identity__Address: http://identity-service:8080/
      ReverseProxy__Clusters__transactionCluster__Destinations__transaction__Address: http://transaction-service:8080/
      ReverseProxy__Clusters__auditlogCluster__Destinations__destination1__Address: http://auditlog-service:8080/
      ReverseProxy__Clusters__platformCluster__Destinations__platform__Address: http://platform-service:8080/
      OpenApiServices__Identity: http://identity-service:8080
      OpenApiServices__Transaction: http://transaction-service:8080
      OpenApiServices__AuditLog: http://auditlog-service:8080
      OpenApiServices__Platform: http://platform-service:8080
    ports:
      - "5193:8080"
  
  # ========================
  # Frontend
  # ========================
  web-admin-react:
    image: ghcr.io/liananddandan/web-admin-react:${WEB_ADMIN_REACT_VERSION}
    container_name: fintrack-web-admin-react
    depends_on:
      gateway:
        condition: service_started
    ports:
      - "3000:80"
    
  web-portal-react:
    image: ghcr.io/liananddandan/web-portal-react:${WEB_PORTAL_REACT_VERSION}
    container_name: fintrack-web-portal-react
    depends_on:
      gateway:
        condition: service_started
    ports:
      - "3001:80"

  web-account-react:
    image: ghcr.io/liananddandan/web-account-react:${WEB_ACCOUNT_REACT_VERSION}
    container_name: fintrack-web-account-react
    depends_on:
      gateway:
        condition: service_started
    ports:
      - "3010:80"


  platform-admin-web:
    image: ghcr.io/liananddandan/platform-admin-web:${PLATFORM_ADMIN_WEB_VERSION}
    container_name: fintrack-platform-admin-web
    depends_on:
      gateway:
        condition: service_started
    ports:
      - "3013:80"
      
volumes:
  mysql_data: