FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
COPY apps ./apps

RUN npm install
RUN npm run build -w apps/platform-admin-web

FROM nginx:alpine
COPY apps/platform-admin-web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/platform-admin-web/dist /usr/share/nginx/html
EXPOSE 80