CREATE DATABASE IF NOT EXISTS fintrack_identity;
CREATE DATABASE IF NOT EXISTS fintrack_transaction;
CREATE DATABASE IF NOT EXISTS fintrack_audit;
CREATE DATABASE IF NOT EXISTS fintrack_notification;
CREATE DATABASE IF NOT EXISTS fintrack_platform;