name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check config
        run: |
          [ -n "${{ vars.VPS_HOST }}" ] && echo "VPS_HOST exists" || echo "VPS_HOST missing"
          [ -n "${{ vars.VPS_USERNAME }}" ] && echo "VPS_USERNAME exists" || echo "VPS_USERNAME missing"
          [ -n "${{ vars.VPS_PORT }}" ] && echo "VPS_PORT exists" || echo "VPS_PORT missing"
          [ -n "${{ secrets.VPS_SSH_KEY }}" ] && echo "VPS_SSH_KEY exists" || echo "VPS_SSH_KEY missing"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ vars.VPS_PORT }}
          script: |
            set -e
            cd ~/FinTrack-Microservices
            git pull
            docker compose up -d --build
            docker image prune -f