name: .NET 9 CI

on:
  push:
    branches:
      - main
      - feature/identity-service
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 123456
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          
      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025
      
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK 9.0.300
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.300
          
      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          
      - name: Wait for MySQL to be healthy
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -P 3307 -uroot -p123456 --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore
        
      - name: Create required databases
        run: |
          mysql -h 127.0.0.1 -P 3307 -uroot -p123456 -e "
            CREATE DATABASE IF NOT EXISTS identity_test;
          "
          
      - name: Apply EF Core migration to identity_test
        run: |
          dotnet ef database update \
            --project Services/IdentityService/IdentityService.csproj \
            --startup-project Services/IdentityService/IdentityService.csproj \
            --context IdentityService.Infrastructure.Persistence.ApplicationIdentityDbContext \
            -- --connectionString "server=127.0.0.1;port=3307;database=identity_test;user=root;password=123456"
      
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
